apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: p1yljc92f-python-gitops
  description: This is GitOps manifest for p1yljc92f-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=p1yljc92f-python
    backstage.io/kubernetes-id: p1yljc92f-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: p1yljc92f-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:p1yljc92f-python
